/**
 * @file    app_menu_power.c
 * @brief   Power management callback overrides for app_menu (shutdown + wakeup)
 *
 * @details Implements the callback functions required by the BSP power module.
 *          These handle the proper shutdown sequence (sensor sleep, display off)
 *          and wakeup sequence (reinitialize peripherals, restore menu state).
 */

#include "../../App/Inc/app_menu.h"
#include "../../Bsp/Inc/bsp_power.h"
#include "../../App/Inc/app_splash.h"
#include "../../../Lib/ST7735/st7735.h"

/** @brief Background color (dark navy blue) */
#define COLOR_BG  ST7735_COLOR565(10, 20, 46)

/** @brief LCD backlight control port */
#define LCD_BL_PORT   GPIOB

/** @brief LCD backlight control pin */
#define LCD_BL_PIN    GPIO_PIN_10

/** @brief Pointer to the currently active menu page */
extern const MenuPage_t* current_page;

/** @brief Main/root menu page structure */
extern const MenuPage_t  page_main;

/** @brief Training mode state flag (0 = menu, 1 = training active) */
extern volatile uint8_t training_is;

/** @brief Current cursor position on the active menu page */
extern volatile uint8_t cursor_pos;

/** @brief Flag indicating the menu page has changed (triggers redraw) */
extern uint8_t page_changed;

/**
 * @brief Shutdown callback - prepares system for STANDBY mode entry
 *
 * This function is called by the BSP power module when the system
 * is about to enter STANDBY low-power mode. It performs the following
 * shutdown sequence:
 * 1. Exits training mode if active
 * 2. Turns off status LEDs
 * 3. Shows shutdown animation on display
 * 4. Puts the MPU9250 IMU into sleep mode
 * 5. Turns off LCD backlight
 *
 * @note This is a callback function registered with the BSP power module.
 *       It should not be called directly by application code.
 */
void bsp_power_on_shutdown_callback(void)
{
    /** Exit training mode if currently active */
    training_is = 0;

    /** Turn off status indicator LEDs */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET); /**< LED1 OFF */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_RESET); /**< LED2 OFF */

    /** Display shutdown animation sequence */
    app_splash_show_shutdown();

    /** Put MPU9250 IMU into sleep mode to conserve power */
    uint8_t sleep_cmd = 0x40; /**< SLEEP bit set in PWR_MGMT_1 register */
    stm32_i2c_write(0x68, MPU9250_PWR_MGMT_1, 1, &sleep_cmd);
    HAL_Delay(10); /**< Allow time for sleep command to take effect */

    /** Turn off LCD backlight to save power */
    HAL_GPIO_WritePin(LCD_BL_PORT, LCD_BL_PIN, GPIO_PIN_RESET);
}

/**
 * @brief Wakeup callback - restores system state after STANDBY exit
 *
 * This function is called by the BSP power module when the system
 * wakes up from STANDBY low-power mode. It performs the following
 * wakeup sequence:
 * 1. Reinitializes SPI1 peripheral (lost during STANDBY)
 * 2. Reinitializes ST7735 display controller
 * 3. Turns on LCD backlight
 * 4. Wakes up the MPU9250 IMU from sleep mode
 * 5. Restores status LED states
 * 6. Resets menu to main page
 * 7. Shows short wake splash screen
 *
 * @note This is a callback function registered with the BSP power module.
 *       It should not be called directly by application code.
 * @note SPI1 and display must be reinitialized because STANDBY mode
 *       resets all peripheral registers.
 */
void bsp_power_on_wakeup_callback(void)
{
    /**
     * Reinitialize SPI1 peripheral.
     * MX_SPI1_Init() is declared locally because the SPI init function
     * is normally generated by CubeMX in main.c and not exposed in a header.
     */
    extern void MX_SPI1_Init(void);
    MX_SPI1_Init();

    /** Reinitialize ST7735 display controller with default settings */
    ST7735_Init();

    /** Turn on LCD backlight */
    HAL_GPIO_WritePin(LCD_BL_PORT, LCD_BL_PIN, GPIO_PIN_SET);

    /** Wake up MPU9250 IMU from sleep mode */
    uint8_t wake_cmd = 0x00; /**< SLEEP bit cleared in PWR_MGMT_1 register */
    stm32_i2c_write(0x68, MPU9250_PWR_MGMT_1, 1, &wake_cmd);
    HAL_Delay(100); /**< Allow time for IMU to wake up and stabilize */

    /** Restore status LED states (LED2 OFF, LED1 ON) */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_RESET); /**< LED2 OFF */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);   /**< LED1 ON */

    /** Reset menu state to main page */
    current_page = &page_main;
    cursor_pos   = 0;
    page_changed = 1; /**< Trigger menu redraw on next cycle */

    /** Display short wake splash screen */
    app_splash_show_wake();
}
